project_id = "shqclgwsgmlnimcggxch"

[functions.export-geojson]
verify_jwt = true

[functions.auth-login]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.assign-form]
verify_jwt = true

[functions.get-assigned-users]
verify_jwt = true
