project_id = "shqclgwsgmlnimcggxch"

[functions.export-geojson]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.verify-password]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-register]
verify_jwt = false
